/* eslint-disable @next/next/no-img-element */
import Head from "next/head";
import useSWR from "swr";
import styles from "../styles/Home.module.css";
export default function Home({ users }) {
  const fetcher = (...args) => fetch(...args).then((res) => res.json());
  const { data, error, isLoading } = useSWR(
    `http://localhost:3000/api/movies/`,
    fetcher
  );
  if (error) return <div className={styles.main}>failed to load</div>;
  if (isLoading) return <div className={styles.main}>loading...</div>;
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className="grid">
          {data.map((e, i) => {
            return (
              <div key={i}>
                <h2 className="bg-red-500 rounded-lg px-4">
                  {i + 1}. {e.title} ({e.year})
                </h2>
                <div className="flex gap-4 my-4">
                  <img
                    className="w-24 aspect-square items-center"
                    src={e.poster}
                    alt="#"
                  />
                  <h1 className="text-justify">{e.fullplot}</h1>
                </div>
              </div>
            );
          })}
        </div>
      </main>
    </>
  );
}
// export async function getServerSideProps() {
//   try {
//     const client = await clientPromise;
//     const db = client.db("sample_mflix");
//     const users = await db
//       .collection("movies")
//       .find({})
//       .sort()
//       .limit(100)
//       .toArray();

//     return {
//       props: { users: JSON.parse(JSON.stringify(users)) },
//     };
//   } catch (e) {
//     console.error(e);
//   }
// }
